pub(in crate::ui) mod dashboard;
pub(in crate::ui) mod containers;
pub(in crate::ui) mod inspect;
pub(in crate::ui) mod logs;
pub(in crate::ui) mod registry;
pub(in crate::ui) mod servers;
pub(in crate::ui) mod stacks;
pub(in crate::ui) mod templates;
pub(in crate::ui) mod themes;
